### ISSUE TITLE
Range slider gets stuck by function call in `onValueChange` prop

### ISSUE THREAD

**Issue by jacquesdev** [Sharcoux/slider#83] opened 2023-10-09 13:32 UTC
**Describe the bug**
This issue is related to the original question I asked, https://github.com/Sharcoux/slider/issues/80, but I wasn't able to reproduce it at the time. I've now finally been able to do that. It was working in my code in v6, but stopped working when upgrading to v7, and I wasn't sure what it was. I initially called console.log at steps a) onSlidingStart, b) onValueChanged and c) onSlidingComplete. I noticed that when I called a function (in this case useRef setState) inside onValueChanged, it would never call c, and thus the slider seems to be stuck. I have a temp function I call to update the UI in onValueChanged before finally changing the value in onSlidingComplete, and in upgrading it got stuck. 

**To Reproduce**
- Go to [this Snack](https://snack.expo.dev/ZLs6_jPx4)

**Expected behavior**
Range slider should be scrollable after upgrading to v7 of the plugin

**Please complete the following information:**
 - OS: iOS (seems to be Android/web too) while looking at the snack
 - @react-native-assets/slider version : latest (but suspect it's from 7 updwards)

**Comment by Sharcoux** [comment] 2023-10-09 14:11
The problem is there: `range={[13, 21]}`
On every render, this generates a new array. This is interpreted as a reassignment of the current slider value, making it "stuck" to its initial location

**Comment by jacquesdev** [comment] 2023-10-09 14:26
@Sharcoux - ok thanks, let me investigate a bit more then why the upgrade seems to break it.

**Comment by Sharcoux** [comment] 2023-10-09 14:29
The old version had a bug where it was not possible to reassign the slider value from what I remember.

**Comment by jacquesdev** [comment] 2023-10-09 14:58
This is probably a stupid question - but what value should range then have? The docs seem to suggest range={[0, 1]} so just wanted to understand

**Comment by Sharcoux** [comment] 2023-10-09 15:21
You misunderstand the problem.

You can solve this with, for instance: `const range = React.useMemo(() => [0, 1], [])`

Or define the range as a const outside the component render function

Or use `const range = React.useRef([0, 1]).current` 

Anything that will rely on a fix reference.

To understand the problem, you need a good understanding of what we mean by "comparison by value or by reference", and a good comprehension of React hooks render cycle.

**Closed** 2023-10-09 21:12 UTC
