### ISSUE TITLE
`onSlidingComplete` callback doesn't always execute for RangeSlider component

### ISSUE THREAD

**Issue by wzeiher-rtg** [Sharcoux/slider#88] opened 2023-10-26 14:07 UTC
**Describe the bug**
When the user releases the thumb on the range slider, the `onSlidingComplete` callback doesn't always get called. This usually happens when you move the slider slightly and frequently. But this is happening frequently enough where I don't think the slider is usable for our use case

**To Reproduce**
- Go to [this Snack](https://snack.expo.dev/@sharcoux/sharcoux-slider-demo)
- Edit the model to reproduce the issue
- Save your changes and paste the link here:

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: iOS and Android
 - @react-native-assets/slider version [if you are sure that you are on the latest version, write "latest"]

**Additional context**

**Comment by Sharcoux** [comment] 2023-10-26 14:17
I couldn't reproduce the issue. Can you edit the provided snack expo to show a test case that reproduces the problem? I'll also need you to confirm the impacted platforms, and the component (range slider, normal slider, or both?)

**Comment by Sharcoux** [comment] 2023-10-31 20:05
The issue couldn't be reproduced and got no news from the OP. I'll close the issue.

**Closed by Sharcoux** 2023-10-31 20:05 UTC
